"""GENERADO por tools/generate-mmio desde 1.isa/mmio_map_v1.vh. No editar.
"""

from __future__ import annotations

MMIO_MEM_BASE = 0x00000000
MMIO_MEM_SIZE_SDRAM = 0x02000000
MMIO_MEM_SIZE_EBR = 0x00008000
MMIO_VIDEO_BASE = 0x80000000
MMIO_SERIAL_BASE = 0x80000200
MMIO_CPU_PERF_BASE = 0x80000300
MMIO_SYSTEM_BASE = 0x80000F00
MMIO_VIDEO_FB_FRONT_OFF = 0x00000000
MMIO_VIDEO_FB_BACK_OFF = 0x00000004
MMIO_VIDEO_SWAP_OFF = 0x00000008
MMIO_VIDEO_STATUS_OFF = 0x0000000C
MMIO_VIDEO_SWAP_COUNT_OFF = 0x00000010
MMIO_VIDEO_HALT_AT_OFF = 0x00000014
MMIO_VIDEO_CTRL_OFF = 0x00000018
MMIO_VIDEO_MODE_BLANK = 0x00000000
MMIO_VIDEO_MODE_PATTERN = 0x00000001
MMIO_VIDEO_MODE_SCANOUT = 0x00000002
MMIO_VIDEO_FB_ALIGN = 0x00000004
MMIO_SERIAL_DATA_OFF = 0x00000000
MMIO_SERIAL_STATUS_OFF = 0x00000004
MMIO_SERIAL_PEEK_OFF = 0x00000008
MMIO_PERF_CYCLES_OFF = 0x00000000
MMIO_PERF_RETIRED_OFF = 0x00000004


#: Todas las constantes por nombre, para quien recorra el mapa entero
#: en vez de citar una. Lo usa el test de sincronia.
ALL = {
    "MMIO_MEM_BASE": MMIO_MEM_BASE,
    "MMIO_MEM_SIZE_SDRAM": MMIO_MEM_SIZE_SDRAM,
    "MMIO_MEM_SIZE_EBR": MMIO_MEM_SIZE_EBR,
    "MMIO_VIDEO_BASE": MMIO_VIDEO_BASE,
    "MMIO_SERIAL_BASE": MMIO_SERIAL_BASE,
    "MMIO_CPU_PERF_BASE": MMIO_CPU_PERF_BASE,
    "MMIO_SYSTEM_BASE": MMIO_SYSTEM_BASE,
    "MMIO_VIDEO_FB_FRONT_OFF": MMIO_VIDEO_FB_FRONT_OFF,
    "MMIO_VIDEO_FB_BACK_OFF": MMIO_VIDEO_FB_BACK_OFF,
    "MMIO_VIDEO_SWAP_OFF": MMIO_VIDEO_SWAP_OFF,
    "MMIO_VIDEO_STATUS_OFF": MMIO_VIDEO_STATUS_OFF,
    "MMIO_VIDEO_SWAP_COUNT_OFF": MMIO_VIDEO_SWAP_COUNT_OFF,
    "MMIO_VIDEO_HALT_AT_OFF": MMIO_VIDEO_HALT_AT_OFF,
    "MMIO_VIDEO_CTRL_OFF": MMIO_VIDEO_CTRL_OFF,
    "MMIO_VIDEO_MODE_BLANK": MMIO_VIDEO_MODE_BLANK,
    "MMIO_VIDEO_MODE_PATTERN": MMIO_VIDEO_MODE_PATTERN,
    "MMIO_VIDEO_MODE_SCANOUT": MMIO_VIDEO_MODE_SCANOUT,
    "MMIO_VIDEO_FB_ALIGN": MMIO_VIDEO_FB_ALIGN,
    "MMIO_SERIAL_DATA_OFF": MMIO_SERIAL_DATA_OFF,
    "MMIO_SERIAL_STATUS_OFF": MMIO_SERIAL_STATUS_OFF,
    "MMIO_SERIAL_PEEK_OFF": MMIO_SERIAL_PEEK_OFF,
    "MMIO_PERF_CYCLES_OFF": MMIO_PERF_CYCLES_OFF,
    "MMIO_PERF_RETIRED_OFF": MMIO_PERF_RETIRED_OFF,
}
